language: python
python:
    - 2.6
    - 2.7
    - pypy
    - 3.3
install:
    - "pip install ."
    - "pip install -r requirements_test.txt"
script:
    - nosetests
    - ./generators_to_coroutines/examples.py
